name: Build
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: sslteam/blottery-tonex

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Update stack service
        uses: garygrossgarten/github-action-ssh@v0.6.3
        with:
          command: docker service update --force blottery_tonex
          host: ${{ secrets.SWARM_HOST }}
          username: root
          privateKey: ${{ secrets.SWARM_PRIVATE_KEY}}
